_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
criterion:
    value: mae
max_depth:
    value: 50
max_features:
    value: 0.5
max_tfidf_features:
    value: 5
min_samples_leaf:
    value: 3
min_samples_split:
    value: 4
n_estimators:
    value: 100
n_jobs:
    value: -1
oob_score:
    value: true
output_artifact:
    value: random_forest_export
random_seed:
    value: 42
rf_config:
    value: /root/Project-Build-an-ML-Pipeline-Starter/multirun/2024-10-05/09-44-27/2/rf_config.json
stratify_by:
    value: neighbourhood_group
trainval_artifact:
    value: trainval_data.csv:latest
val_size:
    value: 0.2
